### PR TITLE
Add device ID to metric event props (part of #516)

### PR DESCRIPTION
**Pull request by debnil**
This PR adds the device ID to the metric tracker's event properties. Part of #516.

Before: the device ID is the same as the user ID.
Before: device ID equals user ID

After: the device ID is library generated and distinct from the user ID.
After: device ID is machine generated

### CODE REVIEW

**Comment by nikhilsaraf** [comment]
I think the test is failing because the glide.yaml and glide.lock file is missing. Could you add these?
Getting the CircleCI tasks to pass is part of a complete PR.

In general, the broader questions to think about before merging code are:

- does this solve the problem in the bug/feature? If not then is the code deactivated somehow (feature flag / no path to possible execution)? Are there other cases beyond what was specifically mentioned in the bug/feature issue?
- am I comfortable merging this PR to the main branch? (no debug comments or print statements, etc.)
- is this going to cause any regressions? (circleCI, untested features)
- can a new developer get an exact copy of the kelp codebase that I currently have? (dependencies)

Looks good besides this :+1:

**Review by nikhilsaraf — COMMENTED** [review]
I think the test is failing because the glide.yaml and glide.lock file is missing. Could you add these?
Getting the CircleCI tasks to pass is part of a complete PR.

In general, the broader questions to think about before merging code are:

- does this solve the problem in the bug/feature? If not then is the code deactivated somehow (feature flag / no path to possible execution)? Are there other cases beyond what was specifically mentioned in the bug/feature issue?
- am I comfortable merging this PR to the main branch? (no debug comments or print statements, etc.)
- is this going to cause any regressions? (circleCI, untested features)
- can a new developer get an exact copy of the kelp codebase that I currently have? (dependencies)

Looks good besides this :+1:

**Comment by debnil** [comment]
100%. Not sure why the `glide.*` files didn't get added when I committed this PR - just realized this and will add.

**Review by nikhilsaraf — DISMISSED** [review]
super, thanks!

**Review by nikhilsaraf — APPROVED** [review]

**Pull request merged**
